region        = "ap-south-1"
project_name  = "zomato"
project_env   = "production"
instance_type = "t2.micro"
instance_ami  = "ami-0cc9838aa7ab1dce7"
key_name      = "zomato"
domain_name   = "jijinmichael.online"
hostname      = "zomato"
